/* Добавляет 5 новых оружий в DT_Item и в DT_ItemResource под IID:

940018	+0 Сапфировый Кинжал
940019	+0 Меч Шторма
940020	+0 Сапфировый Рунный Меч
940021	+0 Молот Шторма
940022	+0 Меч Крови


Не забудьте закинуть в архив gui.rfs картинку item999.dds
А так же модели и текстуры оружия в папку character/model и character/texture
*/

-- DT_Item:

INSERT INTO [dbo].[DT_Item] ([IID], [IName], [IType], [ILevel], [IDHIT], [IDDD], [IRHIT], [IRDD], [IMHIT], [IMDD], [IHPPlus], [IMPPlus], [ISTR], [IDEX], [IINT], [IMaxStack], [IWeight], [IUseType], [IUseNum], [IRecycle], [IHPRegen], [IMPRegen], [IAttackRate], [IMoveRate], [ICritical], [ITermOfValidity], [ITermOfValidityMi], [IDesc], [IStatus], [IFakeID], [IFakeName], [IUseMsg], [IRange], [IUseClass], [IDropEffect], [IUseLevel], [IUseEternal], [IUseDelay], [IUseInAttack], [IIsEvent], [IIsIndict], [IAddWeight], [ISubType], [IIsCharge], [INationOp], [IPShopItemType], [IQuestNo], [IIsTest], [IQuestNeedCnt], [IContentsLv], [IIsConfirm], [IIsSealable], [IAddDDWhenCritical], [mSealRemovalNeedCnt], [mIsPracticalPeriod], [mIsReceiveTown], [IIsReinforceDestroy], [IAddPotionRestore], [IAddMaxHpWhenTransform], [IAddMaxMpWhenTransform], [IAddAttackRateWhenTransform], [IAddMoveRateWhenTransform], [ISupportType], [ITermOfValidityLv], [mIsUseableUTGWSvr], [IAddShortAttackRange], [IAddLongAttackRange], [IWeaponPoisonType], [IDPV], [IMPV], [IRPV], [IDDV], [IMDV], [IRDV], [IHDPV], [IHMPV], [IHRPV], [IHDDV], [IHMDV], [IHRDV], [ISubDDWhenCritical], [IGetItemFeedback], [IEnemySubCriticalHit], [IIsPartyDrop], [IMaxBeadHoleCount], [ISubTypeOption], [mIsDeleteArenaSvr]) VALUES (940018, N'+0 Сапфировый Кинжал', 1, 3, 14, N'4D7+6', 0, N'0', 0, N'0', 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 0, 0, 100, 0, 0, 10000, 0, N'Сапфировый кинжал\nИскрящийся клинок силы, в котором затаилась магия драгоценных камней.\n\nБазовый уровень атаки 14.', 3, 940018, N'Кинжал', N'Вы взяли в руку кинжал.', 150, 255, 2000, 0, 0, 1000, 0, '0', '0', 0, 0, '0', 1152921504606846975, 0, 0, '0', 0, 0, '0', '0', 0, 0, '0', '0', '0', 0, 0, 0, 0, 0, 0, 0, '1', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, '0', 5, 0, '0');
INSERT INTO [dbo].[DT_Item] ([IID], [IName], [IType], [ILevel], [IDHIT], [IDDD], [IRHIT], [IRDD], [IMHIT], [IMDD], [IHPPlus], [IMPPlus], [ISTR], [IDEX], [IINT], [IMaxStack], [IWeight], [IUseType], [IUseNum], [IRecycle], [IHPRegen], [IMPRegen], [IAttackRate], [IMoveRate], [ICritical], [ITermOfValidity], [ITermOfValidityMi], [IDesc], [IStatus], [IFakeID], [IFakeName], [IUseMsg], [IRange], [IUseClass], [IDropEffect], [IUseLevel], [IUseEternal], [IUseDelay], [IUseInAttack], [IIsEvent], [IIsIndict], [IAddWeight], [ISubType], [IIsCharge], [INationOp], [IPShopItemType], [IQuestNo], [IIsTest], [IQuestNeedCnt], [IContentsLv], [IIsConfirm], [IIsSealable], [IAddDDWhenCritical], [mSealRemovalNeedCnt], [mIsPracticalPeriod], [mIsReceiveTown], [IIsReinforceDestroy], [IAddPotionRestore], [IAddMaxHpWhenTransform], [IAddMaxMpWhenTransform], [IAddAttackRateWhenTransform], [IAddMoveRateWhenTransform], [ISupportType], [ITermOfValidityLv], [mIsUseableUTGWSvr], [IAddShortAttackRange], [IAddLongAttackRange], [IWeaponPoisonType], [IDPV], [IMPV], [IRPV], [IDDV], [IMDV], [IRDV], [IHDPV], [IHMPV], [IHRPV], [IHDDV], [IHMDV], [IHRDV], [ISubDDWhenCritical], [IGetItemFeedback], [IEnemySubCriticalHit], [IIsPartyDrop], [IMaxBeadHoleCount], [ISubTypeOption], [mIsDeleteArenaSvr]) VALUES (940019, N'+0 Меч Шторма', 1, 3, 13, N'3D8+7', 0, N'0', 0, N'0', 0, 0, 0, 0, 0, 0, 90, 0, 0, 0, 0, 0, 0, 0, 0, 10000, 0, N'Меч Шторма\nВихрь стали и молний в ваших руках, грозящий сокрушить врагов с небесной яростью.\n\nБазовый уровень атаки 13.', 3, 940019, N'Меч', N'Вы взяли в руку меч.', 150, 255, 2000, 0, 0, 1000, 0, '0', '0', 0, 0, '0', 1152921504606846975, 0, 0, '0', 0, 0, '0', '0', 0, 0, '0', '0', '0', 0, 0, 0, 0, 0, 0, 0, '1', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, '0', 5, 0, '0');
INSERT INTO [dbo].[DT_Item] ([IID], [IName], [IType], [ILevel], [IDHIT], [IDDD], [IRHIT], [IRDD], [IMHIT], [IMDD], [IHPPlus], [IMPPlus], [ISTR], [IDEX], [IINT], [IMaxStack], [IWeight], [IUseType], [IUseNum], [IRecycle], [IHPRegen], [IMPRegen], [IAttackRate], [IMoveRate], [ICritical], [ITermOfValidity], [ITermOfValidityMi], [IDesc], [IStatus], [IFakeID], [IFakeName], [IUseMsg], [IRange], [IUseClass], [IDropEffect], [IUseLevel], [IUseEternal], [IUseDelay], [IUseInAttack], [IIsEvent], [IIsIndict], [IAddWeight], [ISubType], [IIsCharge], [INationOp], [IPShopItemType], [IQuestNo], [IIsTest], [IQuestNeedCnt], [IContentsLv], [IIsConfirm], [IIsSealable], [IAddDDWhenCritical], [mSealRemovalNeedCnt], [mIsPracticalPeriod], [mIsReceiveTown], [IIsReinforceDestroy], [IAddPotionRestore], [IAddMaxHpWhenTransform], [IAddMaxMpWhenTransform], [IAddAttackRateWhenTransform], [IAddMoveRateWhenTransform], [ISupportType], [ITermOfValidityLv], [mIsUseableUTGWSvr], [IAddShortAttackRange], [IAddLongAttackRange], [IWeaponPoisonType], [IDPV], [IMPV], [IRPV], [IDDV], [IMDV], [IRDV], [IHDPV], [IHMPV], [IHRPV], [IHDDV], [IHMDV], [IHRDV], [ISubDDWhenCritical], [IGetItemFeedback], [IEnemySubCriticalHit], [IIsPartyDrop], [IMaxBeadHoleCount], [ISubTypeOption], [mIsDeleteArenaSvr]) VALUES (940020, N'+0 Сапфировый Рунный Меч', 1, 3, 18, N'8D7+7', 0, N'0', 0, N'0', 0, 0, 0, 0, 0, 0, 110, 0, 0, 0, 0, 0, 0, 0, 0, 10000, 0, N'Сапфировый рунный меч\nВоплощение стихийной мощи с магическими рунами, готовыми раскрывать тайны ваших врагов.\n\nБазовый уровень атаки 18.', 3, 940020, N'Меч', N'Вы взяли в руку меч.', 150, 255, 2000, 0, 0, 1000, 0, '0', '0', 0, 0, '0', 1152921504606846975, 0, 0, '0', 0, 0, '0', '0', 0, 0, '0', '0', '0', 0, 0, 0, 0, 0, 0, 0, '1', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, '0', 5, 0, '0');
INSERT INTO [dbo].[DT_Item] ([IID], [IName], [IType], [ILevel], [IDHIT], [IDDD], [IRHIT], [IRDD], [IMHIT], [IMDD], [IHPPlus], [IMPPlus], [ISTR], [IDEX], [IINT], [IMaxStack], [IWeight], [IUseType], [IUseNum], [IRecycle], [IHPRegen], [IMPRegen], [IAttackRate], [IMoveRate], [ICritical], [ITermOfValidity], [ITermOfValidityMi], [IDesc], [IStatus], [IFakeID], [IFakeName], [IUseMsg], [IRange], [IUseClass], [IDropEffect], [IUseLevel], [IUseEternal], [IUseDelay], [IUseInAttack], [IIsEvent], [IIsIndict], [IAddWeight], [ISubType], [IIsCharge], [INationOp], [IPShopItemType], [IQuestNo], [IIsTest], [IQuestNeedCnt], [IContentsLv], [IIsConfirm], [IIsSealable], [IAddDDWhenCritical], [mSealRemovalNeedCnt], [mIsPracticalPeriod], [mIsReceiveTown], [IIsReinforceDestroy], [IAddPotionRestore], [IAddMaxHpWhenTransform], [IAddMaxMpWhenTransform], [IAddAttackRateWhenTransform], [IAddMoveRateWhenTransform], [ISupportType], [ITermOfValidityLv], [mIsUseableUTGWSvr], [IAddShortAttackRange], [IAddLongAttackRange], [IWeaponPoisonType], [IDPV], [IMPV], [IRPV], [IDDV], [IMDV], [IRDV], [IHDPV], [IHMPV], [IHRPV], [IHDDV], [IHMDV], [IHRDV], [ISubDDWhenCritical], [IGetItemFeedback], [IEnemySubCriticalHit], [IIsPartyDrop], [IMaxBeadHoleCount], [ISubTypeOption], [mIsDeleteArenaSvr]) VALUES (940021, N'+0 Молот Шторма', 1, 3, 17, N'7D8+7', 0, N'0', 0, N'0', 0, 0, 0, 0, 0, 0, 200, 0, 0, 0, 0, 0, 0, 0, 0, 10000, 0, N'Молот Шторма\nГромовой молот, что разбивает землю и небеса, призывая мощь бури на поле битвы.\n\nБазовый уровень атаки 17.', 3, 940021, N'Молот', N'Вы взяли в руку молот.', 150, 255, 2000, 0, 0, 1000, 0, '0', '0', 0, 0, '0', 1152921504606846975, 0, 0, '0', 0, 0, '0', '0', 0, 0, '0', '0', '0', 0, 0, 0, 0, 0, 0, 0, '1', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, '0', 5, 0, '0');
INSERT INTO [dbo].[DT_Item] ([IID], [IName], [IType], [ILevel], [IDHIT], [IDDD], [IRHIT], [IRDD], [IMHIT], [IMDD], [IHPPlus], [IMPPlus], [ISTR], [IDEX], [IINT], [IMaxStack], [IWeight], [IUseType], [IUseNum], [IRecycle], [IHPRegen], [IMPRegen], [IAttackRate], [IMoveRate], [ICritical], [ITermOfValidity], [ITermOfValidityMi], [IDesc], [IStatus], [IFakeID], [IFakeName], [IUseMsg], [IRange], [IUseClass], [IDropEffect], [IUseLevel], [IUseEternal], [IUseDelay], [IUseInAttack], [IIsEvent], [IIsIndict], [IAddWeight], [ISubType], [IIsCharge], [INationOp], [IPShopItemType], [IQuestNo], [IIsTest], [IQuestNeedCnt], [IContentsLv], [IIsConfirm], [IIsSealable], [IAddDDWhenCritical], [mSealRemovalNeedCnt], [mIsPracticalPeriod], [mIsReceiveTown], [IIsReinforceDestroy], [IAddPotionRestore], [IAddMaxHpWhenTransform], [IAddMaxMpWhenTransform], [IAddAttackRateWhenTransform], [IAddMoveRateWhenTransform], [ISupportType], [ITermOfValidityLv], [mIsUseableUTGWSvr], [IAddShortAttackRange], [IAddLongAttackRange], [IWeaponPoisonType], [IDPV], [IMPV], [IRPV], [IDDV], [IMDV], [IRDV], [IHDPV], [IHMPV], [IHRPV], [IHDDV], [IHMDV], [IHRDV], [ISubDDWhenCritical], [IGetItemFeedback], [IEnemySubCriticalHit], [IIsPartyDrop], [IMaxBeadHoleCount], [ISubTypeOption], [mIsDeleteArenaSvr]) VALUES (940022, N'+0 Меч Крови', 1, 3, 14, N'4D7+8', 0, N'0', 0, N'0', 0, 0, 0, 0, 0, 0, 90, 0, 0, 0, 0, 0, 0, 0, 0, 10000, 0, N'Меч Крови\nПляска крови и железа в вашем владении, жаждущий поглотить души врагов с безбожной страстью.\n\nБазовый уровень атаки 14.', 3, 940022, N'Меч', N'Вы взяли в руку меч.', 150, 255, 2000, 0, 0, 1000, 0, '0', '0', 0, 0, '0', 1152921504606846975, 0, 0, '0', 0, 0, '0', '0', 0, 0, '0', '0', '0', 0, 0, 0, 0, 0, 0, 0, '1', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, '0', 5, 0, '0');

-- DT_ItemResource:

INSERT INTO [dbo].[DT_ItemResource] ([RID], [ROwnerID], [RType], [RFileName], [RPosX], [RPosY]) VALUES (20317, 940018, 2, N'item999.dds', 480, 336);
INSERT INTO [dbo].[DT_ItemResource] ([RID], [ROwnerID], [RType], [RFileName], [RPosX], [RPosY]) VALUES (20318, 940018, 0, N'0', 2, 32);
INSERT INTO [dbo].[DT_ItemResource] ([RID], [ROwnerID], [RType], [RFileName], [RPosX], [RPosY]) VALUES (20319, 940019, 2, N'item999.dds', 528, 336);
INSERT INTO [dbo].[DT_ItemResource] ([RID], [ROwnerID], [RType], [RFileName], [RPosX], [RPosY]) VALUES (20320, 940019, 0, N'0', 3, 34);
INSERT INTO [dbo].[DT_ItemResource] ([RID], [ROwnerID], [RType], [RFileName], [RPosX], [RPosY]) VALUES (20321, 940020, 2, N'item999.dds', 576, 336);
INSERT INTO [dbo].[DT_ItemResource] ([RID], [ROwnerID], [RType], [RFileName], [RPosX], [RPosY]) VALUES (20322, 940020, 0, N'0', 4, 30);
INSERT INTO [dbo].[DT_ItemResource] ([RID], [ROwnerID], [RType], [RFileName], [RPosX], [RPosY]) VALUES (20323, 940021, 2, N'item999.dds', 624, 336);
INSERT INTO [dbo].[DT_ItemResource] ([RID], [ROwnerID], [RType], [RFileName], [RPosX], [RPosY]) VALUES (20324, 940021, 0, N'0', 4, 31);
INSERT INTO [dbo].[DT_ItemResource] ([RID], [ROwnerID], [RType], [RFileName], [RPosX], [RPosY]) VALUES (20325, 940022, 2, N'item999.dds', 672, 336);
INSERT INTO [dbo].[DT_ItemResource] ([RID], [ROwnerID], [RType], [RFileName], [RPosX], [RPosY]) VALUES (20326, 940022, 0, N'0', 4, 32);

--By Victor Pavlov

